Repository NebulaSS13/Nebula, pull requests merged in 2021-07, with the labels that each got.

#1800 Ported Polaris scaling modifier vaules.
  mods/content/scaling_descriptors.dm
Labels: ready for review, stable

#1748 Slash and burn pass on loadout.
  code/__defines/culture.dm
  code/controllers/subsystems/jobs.dm
  code/datums/outfits/equipment/survival_box.dm
  code/datums/outfits/outfit.dm
  code/game/objects/items/passport.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/lunchbox.dm
  code/modules/client/preference_setup/background/01_culture.dm
  code/modules/client/preference_setup/general/03_equipment.dm
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/client/preference_setup/loadout/lists/augmentations.dm
  code/modules/client/preference_setup/loadout/lists/clothing.dm
  code/modules/client/preference_setup/loadout/lists/earwear.dm
  code/modules/client/preference_setup/loadout/lists/eyegear.dm
  code/modules/client/preference_setup/loadout/lists/footwear.dm
  code/modules/client/preference_setup/loadout/lists/gloves.dm
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/client/preference_setup/loadout/lists/misc.dm
  code/modules/client/preference_setup/loadout/lists/storage.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/client/preference_setup/loadout/lists/tactical.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/client/preference_setup/loadout/lists/utility.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/clothing/glasses/sunglasses.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/species/species.dm
  code/modules/submaps/submap_join.dm
  code/unit_tests/loadout_tests.dm
  maps/exodus/exodus_loadout.dm
  maps/tradeship/tradeship_loadouts.dm
  maps/~mapsystem/maps.dm
  mods/content/corporate/datum/loadout.dm
  mods/mobs/dionaea/datums/loadout.dm
  mods/species/neoavians/clothing.dm
  mods/species/vox/gear/gear_mask.dm
  nebula.dme
Labels: ready for review

#1795 Staging fixes.
  code/game/objects/effects/fluids.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/fabrication/fabricator_ui.dm
  code/modules/overmap/contacts/_contacts.dm
  code/modules/overmap/contacts/contact_sensors.dm
  code/modules/overmap/ships/computers/ship.dm
  code/modules/overmap/ships/ship.dm
  code/modules/power/fusion/_setup.dm
  code/modules/power/fusion/core/_core.dm
  code/modules/power/fusion/fusion_reactions.dm
  code/unit_tests/materials.dm
  maps/tradeship/tradeship-1.dmm
Labels: ready for review

#1802 Swaps a bunch of loops out for visible and audible message proc.
  code/game/machinery/vending/_vending.dm
  code/game/objects/effects/mines.dm
  code/game/objects/item.dm
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/shooting_range.dm
  code/game/objects/items/weapons/implants/implantchair.dm
  code/modules/mob/living/silicon/robot/analyzer.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/power/breaker_box.dm
  code/modules/power/singularity/singularity.dm
  code/modules/reagents/reagent_containers/syringes.dm
Labels: ready for review

#1798 Fixes railing colours.
  code/game/objects/structures/_structure_materials.dm
  code/game/objects/structures/railing.dm
Labels: ready for review, stable

#1807 Drying Improvements and Recipe Fruit Expansion
  code/datums/recipe.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/modules/hydroponics/grown.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: awaiting author

#1804 Facial hair now checks for a bodytype, rather than pronouns
  code/modules/client/preference_setup/general/01_basic.dm
  code/modules/client/preference_setup/general/02_body.dm
  code/modules/mob/living/carbon/human/appearance.dm
  code/modules/species/species.dm
  code/modules/species/species_shapeshifter.dm
Labels: awaiting author

#1799 Ports composite sounds from Aurora.
  code/datums/composite_sounds/_composite_sound.dm
  nebula.dme
Labels: ready for review

#1809 Swapped display_name to name for codex entries.
  code/controllers/subsystems/initialization/codex.dm
  code/modules/codex/categories/_category.dm
  code/modules/codex/categories/category_cocktails.dm
  code/modules/codex/categories/category_fusion_reaction.dm
  code/modules/codex/categories/category_languages.dm
  code/modules/codex/categories/category_reactions.dm
  code/modules/codex/categories/category_recipes.dm
  code/modules/codex/categories/category_skills.dm
  code/modules/codex/categories/category_species.dm
  code/modules/codex/categories/category_substances.dm
  code/modules/codex/categories/category_surgery.dm
  code/modules/codex/codex_client.dm
  code/modules/codex/entries/_codex_entry.dm
  code/modules/codex/entries/atmospherics.dm
  code/modules/codex/entries/codex.dm
  code/modules/codex/entries/guns.dm
  code/modules/codex/entries/mobs.dm
  code/modules/codex/entries/stacks.dm
  code/modules/codex/entries/tools.dm
  code/modules/organs/ailments/ailment_codex.dm
  mods/content/psionics/datum/codex.dm
  mods/content/xenobiology/slime/slime_codex.dm
  mods/species/ascent/datum/codex.dm
Labels: ready for review

#1761 Ports and updates aspect system from Europa.
  code/__defines/aspects.dm
  code/__defines/colors.dm
  code/controllers/configuration.dm
  code/controllers/subsystems/jobs.dm
  code/datums/wires/wires.dm
  code/game/antagonist/station/changeling.dm
  code/modules/admin/admin_verbs.dm
  code/modules/aspects/aspects.dm
  code/modules/aspects/aspects_amputations.dm
  code/modules/aspects/aspects_handicaps.dm
  code/modules/aspects/aspects_perks.dm
  code/modules/aspects/aspects_prosthetic_limbs.dm
  code/modules/aspects/aspects_prosthetic_organs.dm
  code/modules/client/client_color.dm
  code/modules/client/client_color_definitions.dm
  code/modules/client/preference_setup/_defines.dm
  code/modules/client/preference_setup/general/02_body.dm
  code/modules/client/preference_setup/general/03_aspects.dm
  code/modules/client/preference_setup/general/04_equipment.dm
  code/modules/client/preference_setup/general/05_flavor.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/client/preference_setup/preference_setup.dm
  code/modules/client/preferences.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/mob/observer/eye/blueprints_eye.dm
  code/modules/organs/ailments/faults/fault_visual_impairment.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/organ.dm
  code/modules/organs/prosthetics/prosthetics_manufacturer_models.dm
  code/unit_tests/aspects.dm
  config/example/game_options.txt
  mods/content/corporate/datum/robolimbs.dm
  mods/content/psionics/_psionics.dm
  mods/species/ascent/_ascent.dme
  mods/species/ascent/datum/aspects.dm
  mods/species/utility_frames/_utility_frames.dm
  mods/species/utility_frames/_utility_frames.dme
  mods/species/utility_frames/aspects.dm
  mods/species/vox/_vox.dme
  mods/species/vox/datum/aspects.dm
  nebula.dme
Labels: ready for review

#1808 Declifying spawnpoints.
  code/__defines/misc.dm
  code/controllers/subsystems/jobs.dm
  code/game/jobs/job/_job.dm
  code/modules/client/preference_setup/general/01_basic.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/mob/new_player/new_player.dm
  code/unit_tests/map_tests.dm
  maps/away_sites_testing/away_sites_testing_define.dm
  maps/example/example_define.dm
  maps/ministation/ministation_define.dm
  maps/modpack_testing/modpack_testing_define.dm
  maps/nexus/nexus_define.dm
  maps/tradeship/jobs/command.dm
  maps/tradeship/tradeship_spawnpoints.dm
  maps/~mapsystem/maps.dm
  test/check-paths.sh
Labels: ready for review

#1754 Steals Nyxodile's reimplementation of necrosis surgery + tweaks.
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/organs/external/_external.dm
  code/modules/surgery/necrotic.dm
Labels: ready for review

#1839 constructable trays
  code/game/objects/items/weapons/circuitboards/machinery/portable_atmospherics.dm
Labels: ready for review

#1810 Pruned some loadout stuff I missed in the first big pass.
  code/game/machinery/computer/arcade.dm
  code/game/objects/random/random.dm
  code/modules/client/preference_setup/loadout/lists/misc.dm
  maps/exodus/exodus_loadout.dm
  mods/mobs/dionaea/_dionaea.dme
  mods/mobs/dionaea/datums/loadout.dm
  mods/species/vox/datum/species.dm
  mods/species/vox/gear/gear_mask.dm
Labels: ready for review

#1596 Adds Generic FSM System
  code/datums/datum.dm
  code/datums/extensions/state_machine.dm
  code/datums/state_machine/paper_fortune_fsm.dm
  code/datums/state_machine/state.dm
  code/datums/state_machine/transition.dm
  code/game/objects/items/paper_fortune_teller.dm
  code/modules/power/singularity/singularity.dm
  icons/obj/items/fortune_teller.dmi
  nebula.dme
Labels: ready for review

#1831 Small fixes for vedning UI
  code/game/machinery/vending/_vending.dm
  nano/css/shared.css
  nano/templates/vending_machine.tmpl
Labels: ready for review

#1805 Committing auto-updated VSC settings.json.
  .vscode/settings.json
Labels: ready for review

#1854 Staging fixes.
  code/game/objects/items/weapons/surgery_tools.dm
  code/modules/overmap/spacetravel.dm
  code/modules/projectiles/targeting/targeting_overlay.dm
Labels: ready for review, stable

#1856 Makes Oxygel Detectable to Health Analysers
  code/modules/reagents/chems/chems_medicines.dm
Labels: ready for review

#1855 Bodyfall Sounds
  code/_global_vars/sound.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/species/species_bodytype.dm
  sound/attributions.txt
  sound/foley/meat1.ogg
  sound/foley/meat2.ogg
  sound/foley/metal1.ogg
Labels: ready for review

#1806 Microwave Refactor and Recipe Improvements
  code/datums/composite_sounds/machinery_sounds.dm
  code/datums/recipe.dm
  code/game/machinery/kitchen/microwave.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/Chemistry-Holder.dm
  html/changelogs/MDP-microwave-refactor.yml
  mods/content/xenobiology/food.dm
  nano/js/nano_base_helpers.js
  nano/templates/microwave.tmpl
  nebula.dme
  sound/machines/microwave/microwave-end.ogg
  sound/machines/microwave/microwave-mid1.ogg
  sound/machines/microwave/microwave-mid2.ogg
  sound/machines/microwave/microwave-start.ogg
Labels: ready for review

#1834 Browser cleanup
  code/datums/browser.dm
  code/datums/extensions/multitool/multitool.dm
  code/datums/wires/wires.dm
  code/game/machinery/spaceheater.dm
  code/game/objects/items/weapons/cards_ids.dm
Labels: awaiting author

#1859 Updates pull request template to tgstation and TauCeti version
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready for review

#1853 Stable fixes.
  code/game/machinery/doors/_door.dm
  code/game/machinery/vending/botany.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/weapons/storage/misc.dm
  code/game/objects/objs.dm
  code/modules/clothing/masks/cig_crafting.dm
  code/modules/economy/worth_cash.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/hydroponics/seed_storage.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/surgery/other.dm
  icons/obj/vending.dmi
  maps/random_ruins/exoplanet_ruins/crashed_pod/crashed_pod.dmm
  maps/random_ruins/exoplanet_ruins/hydrobase/hydrobase.dmm
  maps/random_ruins/exoplanet_ruins/lodge/lodge.dmm
Labels: ready for review

#1875 Makes dreamchecker output not in separate tab
  .github/workflows/test.yml
Labels: ready for review

#1873 Fixes some math issues with combustion
  code/modules/ZAS/Fire.dm
Labels: awaiting author

#1837 Canned food interaction update
  code/game/machinery/vending/food.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/goals/definitions/personal_achievement_specific_object.dm
  code/modules/reagents/reagent_containers/food/canned_food.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/items/weapon/knives/opener.dmi
  nebula.dme
Labels: awaiting author

#1888 Adds "Storage" category to the textiles fabricator.
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/specialized.dm
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/items/weapons/storage/wallets.dm
  code/modules/fabrication/designs/textile/storage.dm
  nebula.dme
Labels: ready for review

#1866 SScharacters queue and save file migration changes
  code/controllers/subsystems/initialization/character_setup.dm
  code/datums/mil_ranks.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/client_procs.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/client/preferences.dm
  code/modules/mob/new_player/login.dm
  maps/~mapsystem/map_preferences.dm
Labels: ready for review

#1879 Fab and turf QOL/fixes.
  code/game/objects/items/weapons/RCD.dm
  code/game/turfs/exterior/_exterior.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/space/space.dm
  code/modules/fabrication/_fabricator.dm
  code/modules/fabrication/fabricator_topic.dm
  code/modules/fabrication/fabricator_ui.dm
  code/modules/multiz/turf.dm
  nano/templates/fabricator.tmpl
Labels: ready for review

#1882 Adds stack merge types to material stacks.
  code/modules/materials/material_sheets.dm
Labels: ready for review

#1877 Adds textile fabricator recipes
  code/game/objects/items/weapons/storage/specialized.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/fabrication/designs/textile/job.dm
  code/modules/fabrication/designs/textile/protective.dm
  code/modules/fabrication/designs/textile/storage.dm
  nebula.dme
Labels: ready for review

#1889 Fixes shuttle turf translation
  code/game/turfs/turf_changing.dm
Labels: stable

#1887 Adjusted null wire unit test to skip destroyed/untracked cables.
  code/controllers/subsystems/machines.dm
  code/modules/power/cable.dm
  code/unit_tests/map_tests.dm
Labels: ready for review

#1883 Replaces IV drip sprites with new one
  code/game/objects/structures/iv_drip.dm
  icons/obj/structures/iv_drip.dmi
Labels: ready for review

#1846 Ports radial CPR from Aurora
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  icons/screen/radial.dmi
Labels: ready for review

#1841 switches the integrated maneuvering module to use it's own gas tank
  code/game/objects/items/weapons/tanks/jetpack.dm
  code/modules/clothing/spacesuits/rig/modules/modules.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
Labels: ready for review

#1872 Material processing and use changes.
  code/__defines/flags.dm
  code/datums/supplypacks/engineering.dm
  code/game/machinery/_machines_base/machinery_damage.dm
  code/game/machinery/_machines_base/stock_parts/_stock_parts.dm
  code/game/machinery/_machines_base/stock_parts/stock_parts_interface.dm
  code/game/objects/items/weapons/circuitboards/machinery/mining.dm
  code/game/objects/items/weapons/circuitboards/machinery/pacman.dm
  code/modules/admin/admin_verbs.dm
  code/modules/codex/entries/machinery.dm
  code/modules/materials/definitions/solids/materials_solid_exotic.dm
  code/modules/materials/definitions/solids/materials_solid_ice.dm
  code/modules/materials/definitions/solids/materials_solid_mineral.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/materials_ore.dm
  code/modules/mechs/premade/light.dm
  code/modules/mining/machinery/material_smelter.dm
  code/modules/power/port_gen.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/chems/chems_fuel.dm
  code/modules/reagents/reactions/reaction_grenade_reaction.dm
  code/modules/reagents/reactions/reaction_synthesis.dm
  icons/obj/materials.dmi
  nano/templates/material_processing_smeltery.tmpl
Labels: ready for review

#1836 Modularize lobby menu
  code/controllers/subsystems/ticker.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/asset_cache.dm
  code/modules/client/client_procs.dm
  code/modules/mob/new_player/lobby.dm
  code/modules/mob/new_player/new_player.dm
  html/lobby_titlescreen.html
  maps/~mapsystem/maps.dm
  nebula.dme
Labels: ready for review

#1863 Ports pools from Baystation12
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/structures/drain.dm
  code/game/objects/structures/watercloset.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/game/turfs/turf_fluids.dm
  code/modules/fabrication/designs/pipe/device_pipe_datums.dm
  code/modules/materials/recipes_stacks.dm
  icons/obj/drain.dmi
  icons/obj/tiles.dmi
  icons/obj/watercloset.dmi
  icons/turf/flooring/pool.dmi
Labels: awaiting author

#1924 Updates fuel port sprites by retlaw34
  code/game/objects/structures/fuel_port.dm
  code/modules/overmap/overmap_shuttle.dm
  icons/obj/structures/fuel_port.dmi
  maps/antag_spawn/mercenary/mercenary_base.dmm
  maps/away/casino/casino.dmm
  maps/away/liberia/liberia.dmm
  maps/random_ruins/exoplanet_ruins/marooned/marooned.dmm
  mods/content/generic_shuttles/tanker/tanker.dmm
  nebula.dme
Labels: awaiting author

#1911 nuclear cylinder storage
  code/game/machinery/self_destruct_storage.dm
  code/game/objects/items/weapons/circuitboards/machinery/self_destruct_storage.dm
  code/modules/fabrication/designs/imprinter/designs_misc_circuits.dm
  icons/obj/machines/self_destruct.dmi
  icons/obj/machines/self_destruct_storage.dmi
  nebula.dme
Labels: ready for review

#1822 SSinput
  code/__defines/admin.dm
  code/__defines/colors.dm
  code/__defines/misc.dm
  code/__defines/subsystem-priority.dm
  code/__defines/subsystems.dm
  code/_global_vars/client.dm
  code/_helpers/global_lists.dm
  code/_helpers/sanitize_values.dm
  code/_onclick/click.dm
  code/controllers/configuration.dm
  code/controllers/subsystems/input.dm
  code/datums/movement/movement.dm
  code/game/atoms_movable.dm
  code/game/verbs/ooc.dm
  code/modules/admin/callproc/callproc.dm
  code/modules/admin/spam_prevention.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preference_setup/controls/01_keybindings.dm
  code/modules/client/preference_setup/preference_setup.dm
  code/modules/client/preferences.dm
  code/modules/keybindings/_defines.dm
  code/modules/keybindings/_keybindings.dm
  code/modules/keybindings/admin.dm
  code/modules/keybindings/bindings_atom.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/keybindings/carbon.dm
  code/modules/keybindings/client.dm
  code/modules/keybindings/communication.dm
  code/modules/keybindings/human.dm
  code/modules/keybindings/living.dm
  code/modules/keybindings/mob.dm
  code/modules/keybindings/movement.dm
  code/modules/keybindings/readme.md
  code/modules/keybindings/robot.dm
  code/modules/keybindings/setup.dm
  code/modules/mob/living/silicon/robot/login.dm
  code/modules/mob/login.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/mob_movement.dm
  code/modules/mob/observer/ghost/ghost.dm
  code/modules/mob/typing_indicator.dm
  code/modules/organs/external/_external.dm
  code/modules/pointdefense/pointdefense.dm
  config/example/game_options.txt
  icons/effects/mouse_pointers/examine_pointer.dmi
  interface/interface.dm
  interface/skin.dmf
  nebula.dme
Labels: awaiting author

#1908 Skybox Update
  code/controllers/subsystems/skybox.dm
  code/controllers/subsystems/zcopy.dm
  code/game/turfs/space/space.dm
  code/game/turfs/space/transit.dm
  code/modules/overmap/_defines.dm
  icons/turf/space.dmi
  icons/turf/space_dust_transit.dmi
Labels: ready for review

#1946 Adds very (I hope) noticeable notice about IDB and MDB ignore tags
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready for review

#1935 Adds images and contents list to accessories and closets
  code/_helpers/lists.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/structures/crates_lockers/closets/__closet.dm
  code/modules/clothing/_clothing.dm
Labels: ready for review

#1833 Refactors flamethrowers onto Aurora's version
  code/game/objects/items/weapons/flamethrower.dm
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/game/objects/items/weapons/tools/weldingtool.dm
  icons/obj/flamethrower.dmi
  icons/obj/items/tanks/tank_greyscaled.dmi
  icons/obj/items/tanks/tank_orange.dmi
Labels: awaiting author

#1954 Adjusting drone lights.
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: ready for review

#1952 Fixes #1796.
  code/modules/events/electrical_storm.dm
  code/modules/power/apc.dm
Labels: ready for review

#1945 Adds way to toggle right click menu off for specific mobs
  code/_onclick/click.dm
  code/modules/client/client_procs.dm
  code/modules/mob/login.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/observer/observer.dm
Labels: ready for review
