Repository NebulaSS13/Nebula, pull requests merged in 2022-05, with the labels that each got.

#2271 New year's eve fixes
  code/__defines/misc.dm
  code/_helpers/icons.dm
  code/_onclick/hud/screen_objects.dm
  code/game/machinery/Sleeper.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/game/objects/items/weapons/storage/storage_ui/default.dm
  code/modules/admin/buildmode/areas.dm
  code/modules/admin/callproc/callproc.dm
  code/modules/admin/map_capture.dm
  code/modules/client/client_procs.dm
  code/modules/client/preference_setup/global/preferences.dm
  code/modules/client/ui_style.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/modular_computers/os/subtypes/device.dm
  code/modules/nano/interaction/default.dm
  code/modules/nano/interaction/view.dm
  code/modules/overmap/events/event.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/computers/ship.dm
  code/modules/paperwork/photography.dm
  icons/mob/simple_animal/mouse_brown.dmi
  icons/mob/simple_animal/mouse_gray.dmi
  icons/mob/simple_animal/mouse_white.dmi
  nano/css/shared.css
  test/check-paths.sh
Labels: ready for review

#2326 Fix tail icon key
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: ready for review

#2327 Fixes infinite latencies.
  mods/content/psionics/system/psionics/complexus/complexus_latency.dm
Labels: stable, ready for review

#2329 Fixes reference finder on globals
  code/controllers/subsystems/garbage.dm
Labels: ready for review

#2338 destroy: ..() to return ..()
  code/game/machinery/embedded_controller/embedded_controller_base.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/game/objects/effects/chem/foam.dm
  code/modules/mechs/mech_wreckage.dm
  code/modules/power/solar.dm
Labels: ready for review

#2344 Gating off a division by zero check in gas heat capacity.
  code/modules/materials/_materials.dm
  code/modules/materials/definitions/gasses/_mat_gas.dm
  code/modules/xgm/xgm_gas_mixture.dm
Labels: ready for review

#2340 Standardizing robotize, adding capacity to check against specific species/bodytype.
  code/modules/organs/external/_external.dm
  code/modules/organs/external/head.dm
  code/modules/organs/internal/_internal.dm
  code/modules/organs/internal/brain.dm
  code/modules/organs/internal/eyes.dm
  code/modules/organs/organ.dm
Labels: ready for review

#2336 Added godmode checks to fall damage + dislocating + shock
  code/modules/mob/living/carbon/human/life.dm
  code/modules/multiz/movement.dm
  code/modules/organs/external/_external.dm
Labels: awaiting author

#2341 Blast doors now autoset direction from neighbors.
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/blast_door.dm
Labels: ready for review

#2353 Resets dislocation in rejuvenate.
  code/modules/organs/external/_external.dm
Labels: ready for review

#2347 Blacklisted abstract material types from exoplanet gas selection.
  code/modules/overmap/exoplanets/exoplanet_atmosphere.dm
Labels: ready for review

#2346 Prevents parrots calming down eternally.
  code/modules/mob/living/simple_animal/hostile/retaliate/parrot.dm
Labels: ready for review

#2345 Adds missing blood type to species def.
  code/modules/species/species.dm
Labels: ready for review

#2354 Shuffling around the hardness values that allow recipes.
  code/modules/materials/definitions/solids/materials_solid_organic.dm
  code/modules/materials/material_recipes.dm
Labels: ready for review

#2330 Rejuvenating the heart should now fix it stopping
  code/modules/organs/internal/heart.dm
Labels: ready for review

#2350 Removing broken vendor icon.
  code/game/machinery/vending/botany.dm
  icons/obj/vending.dmi
Labels: ready for review

#2356 Adding safety checking to fluid turf and overlay queuing.
  code/__defines/fluids.dm
Labels: ready for review

#2352 Adds shields to industrial fab, allows buckler crafting.
  code/game/objects/items/weapons/shields.dm
  code/modules/crafting/crafting_recipes/improvised_crafting/crafting_buckler.dm
  code/modules/fabrication/designs/industrial/designs_armour.dm
  code/modules/fabrication/fabricator_industrial.dm
  icons/obj/crafting_icons.dmi
  nebula.dme
Labels: ready for review

#2359 More GC fixes and tweaks from Hearth.
  code/controllers/subsystems/throwing.dm
  code/datums/mind/mind.dm
  code/game/movietitles.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/hostile/bat.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/parrot.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/retaliate.dm
  code/modules/mob/mob.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/modular_computers/computers/modular_computer/assembly_computer.dm
  mods/content/matchmaking/matchmaker.dm
Labels: ready for review

#2360 Lazylists bad_external_organs, applies ref fixes from Hearth.
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_organs.dm
  code/modules/organs/external/_external.dm
Labels: ready for review

#2363 Simplifies and modernizes report access.
  code/game/jobs/access.dm
  code/modules/modular_computers/file_system/programs/generic/deck_management.dm
  code/modules/modular_computers/file_system/reports/deck_reports.dm
  code/modules/modular_computers/file_system/reports/report.dm
  code/modules/modular_computers/file_system/reports/report_field.dm
  code/modules/modular_computers/file_system/reports/warrant.dm
Labels: ready for review

#2367 Replaces simply dmi preview with AnturK's dmi editor vscode extension
  .vscode/extensions.json
  .vscode/settings.json
Labels: ready for review

#2365 Fix GC issues with temperature (+ maybe reactions)
  code/__defines/chemistry.dm
  code/__defines/temperature.dm
  code/game/atoms_init.dm
  code/game/atoms_temperature.dm
  code/game/objects/structures/fires.dm
  code/modules/reagents/reactions/_reaction.dm
Labels: ready for review

#2358 Hearth ref finder tweaks.
  code/controllers/subsystems/garbage.dm
  test/check-paths.sh
Labels: ready for review

#2369 More intuitive airlock/blast door construction
  code/game/machinery/doors/blast_door.dm
  code/game/objects/structures/door_assembly.dm
Labels: ready for review

#2337 Limb dislocation fix + improvements
  code/__defines/damage_organs.dm
  code/game/objects/items/devices/scanners/health.dm
  code/modules/mob/grab/normal/grab_normal.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_verbs.dm
  code/modules/multiz/movement.dm
  code/modules/organs/ailments/ailments_medical.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/external/diagnostics.dm
  code/modules/organs/external/head.dm
  code/modules/organs/external/standard.dm
  code/modules/organs/external/stump.dm
  code/modules/organs/external/tail.dm
  code/modules/organs/external/unbreakable.dm
  mods/species/adherent/organs/organs_external.dm
Labels: ready for review

#2333 Add feedback when wiring zcable + tweaks
  code/game/turfs/simulated.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/turf.dm
  code/modules/multiz/turf.dm
  code/modules/power/cable.dm
  code/modules/power/power.dm
Labels: ready for review

#2380 Assorted power fixes
  code/game/machinery/_machines_base/machine_construction/noninteractive.dm
  code/game/machinery/_machines_base/stock_parts/power/terminal.dm
  code/modules/power/fusion/consoles/core_control.dm
  code/modules/power/terminal.dm
  icons/obj/power.dmi
Labels: ready for review

#2374 Adding a roleplay summary var to species preview.
  code/modules/client/preference_setup/background/01_species.dm
  code/modules/species/species.dm
Labels: ready for review

#2384 Updating staging from stable.
  code/game/turfs/simulated.dm
  code/modules/modular_computers/networking/machinery/mainframe.dm
  mods/content/psionics/system/psionics/complexus/complexus_latency.dm
Labels: ready for review

#2382 Fixes busted do_tool_interaction usage.
  code/modules/organs/external/_external.dm
  code/modules/tools/tool_item.dm
Labels: ready for review

#2392 Fixing rejuvenate not fixing limbs.
  code/modules/organs/external/_external.dm
Labels: ready for review

#2397 Removes AS_ANYTHING macro due no need
  code/__defines/misc.dm
  code/_helpers/icons.dm
  code/_helpers/overmap.dm
  code/_helpers/visual_filters.dm
  code/controllers/subsystems/fluids.dm
  code/controllers/subsystems/mapping.dm
  code/controllers/subsystems/weather.dm
  code/datums/composite_sounds/_composite_sound.dm
  code/datums/movement/mob.dm
  code/datums/recipe.dm
  code/datums/state_machine/state.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/endgame/supermatter_cascade/universe.dm
  code/game/jobs/job/_job.dm
  code/game/objects/structures/tables.dm
  code/game/turfs/simulated.dm
  code/game/turfs/simulated/wall_icon.dm
  code/game/turfs/turf_fluids.dm
  code/game/world_topic_commands.dm
  code/modules/ZAS/Airflow.dm
  code/modules/ZAS/ConnectionGroup.dm
  code/modules/admin/verbs/fluids.dm
  code/modules/atmospherics/atmospherics.dm
  code/modules/atmospherics/components/binary_devices/binary_atmos_base.dm
  code/modules/atmospherics/components/omni_devices/_omni_extras.dm
  code/modules/atmospherics/components/omni_devices/omni_base.dm
  code/modules/atmospherics/components/tvalve.dm
  code/modules/atmospherics/components/unary/vent_pump.dm
  code/modules/atmospherics/components/unary/vent_scrubber.dm
  code/modules/atmospherics/components/valve.dm
  code/modules/atmospherics/he_pipes.dm
  code/modules/atmospherics/pipes.dm
  code/modules/client/preference_setup/general/01_basic.dm
  code/modules/client/preference_setup/global/preferences.dm
  code/modules/events/electrical_storm.dm
  code/modules/maps/map_template.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/modules/_module.dm
  code/modules/mob/login.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_layering.dm
  code/modules/nano/modules/human_appearance.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/computers/helm.dm
  code/modules/power/geothermal/_geothermal.dm
  code/modules/projectiles/targeting/targeting_triggers.dm
  code/modules/shuttles/shuttle.dm
  code/modules/status_conditions/_status_markers.dm
  code/modules/weather/_weather.dm
  code/modules/weather/weather_init.dm
  code/unit_tests/aspects.dm
  code/unit_tests/atmospherics_tests.dm
  code/unit_tests/codex.dm
  code/unit_tests/map_tests.dm
Labels: ready for review

#2372 new sprites for vents and scrubbers
  icons/atmos/vent_pump.dmi
  icons/atmos/vent_scrubber.dmi
  icons/obj/pipe-item.dmi
Labels: ready for review

#2366 Swaps direct level list references out for procs.
  code/_helpers/game.dm
  code/_helpers/turfs.dm
  code/controllers/subsystems/initialization/persistence.dm
  code/datums/helper_datums/teleport.dm
  code/datums/security_state.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/endgame/supermatter_cascade/universe.dm
  code/game/machinery/alarm.dm
  code/game/machinery/camera/tracking.dm
  code/game/machinery/computer/robot.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/teleporter.dm
  code/game/objects/structures/bookcase.dm
  code/modules/admin/verbs/diagnostics.dm
  code/modules/clothing/spacesuits/rig/modules/ninja.dm
  code/modules/events/apc_damage.dm
  code/modules/events/camera_damage.dm
  code/modules/events/computer_update.dm
  code/modules/events/solar_storm.dm
  code/modules/hydroponics/trays/tray_soil.dm
  code/modules/mob/observer/ghost/ghost.dm
  code/modules/mob/observer/observer.dm
  code/modules/nano/nanoui.dm
  code/modules/persistence/persistence_datum.dm
  code/modules/persistence/persistence_datum_book.dm
  code/modules/spells/artifacts/spellbound_servants.dm
  code/modules/spells/spell_code.dm
  code/modules/supermatter/supermatter.dm
Labels: ready for review

#2389 Fixing reagents departing the bloodstream.
  code/modules/client/client_color_definitions.dm
  code/modules/materials/_materials.dm
  code/modules/materials/definitions/liquids/materials_liquid_toxins.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Metabolism.dm
  code/modules/reagents/chems/chems_compounds.dm
  code/modules/reagents/chems/chems_drugs.dm
Labels: ready for review

#2396 Splitting serpentids into their own modpack.
  code/modules/species/species.dm
  maps/exodus/exodus.dm
  maps/ministation/ministation.dm
  maps/modpack_testing/modpack_testing.dm
  maps/tradeship/tradeship.dm
  mods/species/ascent/_ascent.dme
  mods/species/ascent/ascent.dm
  mods/species/ascent/datum/aspects.dm
  mods/species/ascent/datum/culture.dm
  mods/species/ascent/datum/languages.dm
  mods/species/ascent/datum/species.dm
  mods/species/ascent/datum/species_bodytypes.dm
  mods/species/ascent/effects/razorweb.dm
  mods/species/ascent/items/clothing.dm
  mods/species/ascent/items/guns.dm
  mods/species/ascent/items/rig.dm
  mods/species/serpentid/_serpentid.dme
  mods/species/serpentid/datum/attacks.dm
  mods/species/serpentid/datum/species.dm
  mods/species/serpentid/datum/species_bodytypes.dm
  mods/species/serpentid/icons/blood_overlays.dmi
  mods/species/serpentid/icons/body_green.dmi
  mods/species/serpentid/icons/body_grey.dmi
  mods/species/serpentid/icons/eyes.dmi
  mods/species/serpentid/icons/threat.dmi
  mods/species/serpentid/mobs/bodyparts_serpentid.dm
  mods/species/serpentid/serpentid.dm
Labels: ready for review

#2398 Flash refactor.
  code/game/objects/items/devices/flash.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/silicon/robot/inventory.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  nebula.dme
Labels: ready for review

#2401 Pruned abstract psionics powers from faculties.
  mods/content/psionics/system/psionics/faculties/_power.dm
  mods/content/psionics/system/psionics/faculties/coercion.dm
  mods/content/psionics/system/psionics/faculties/energistics.dm
  mods/content/psionics/system/psionics/faculties/psychokinesis.dm
  mods/content/psionics/system/psionics/faculties/redaction.dm
  mods/content/psionics/system/subsystem_psi.dm
Labels: ready for review

#2403 Implements two small todo comments.
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/reagents/chems/chems_compounds.dm
Labels: ready for review

#2404 Swaps damtype strings out for defines.
  code/__defines/damage_organs.dm
  code/__defines/shields.dm
  code/controllers/verbs.dm
  code/game/machinery/deployable.dm
  code/game/objects/auras/starlight.dm
  code/game/objects/items/weapons/flame.dm
  code/game/objects/objs.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/railing.dm
  code/modules/admin/view_variables/helpers.dm
  code/modules/admin/view_variables/topic.dm
  code/modules/blob/blob.dm
  code/modules/clothing/masks/smokable.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/external/head.dm
Labels: ready for review

#2208 Convert a lot of improper noun names to lowercase
  code/game/machinery/OpTable.dm
  code/game/machinery/biogenerator.dm
  code/game/machinery/bodyscanner_display.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/floodlight.dm
  code/game/objects/items/weapons/staff.dm
  code/modules/atmospherics/pipes.dm
  code/modules/awaymissions/exile.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/paperwork/photography.dm
  code/modules/reagents/reagent_containers/condiment.dm
  code/modules/reagents/reagent_containers/dropper.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/xenoarcheaology/tools/equipment.dm
  maps/away/unishi/unishi.dm
  mods/content/government/away_sites/icarus/icarus.dm
Labels: work in progress

#2405 Apparent fix to power usage; harsher unit test
  code/game/atoms_init.dm
  code/game/machinery/_machines_base/machinery_power.dm
  code/modules/xenoarcheaology/artifacts/standalone/autocloner.dm
  code/modules/xenoarcheaology/boulder.dm
  code/unit_tests/power_tests.dm
Labels: ready for review

#2381 Attempting to make organ init more consistent.
  code/modules/mob/living/carbon/human/human_organs.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/internal/_internal.dm
  code/modules/organs/organ.dm
Labels: ready for review

#2393 Fixes anchored mobs being impossible to mousedrag in any circumstances.
  code/_helpers/mobs.dm
  code/_onclick/drag_drop.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/godmode/form_items/wizard_structures.dm
  code/game/machinery/OpTable.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/bodyscanner.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/rechargestation.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/game/objects/structures/mineral_bath.dm
  code/modules/butchery/butchery.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/mob/living/bot/mulebot.dm
  code/modules/mob/living/carbon/human/stripping.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/paperwork/paper.dm
  code/modules/recycling/disposal.dm
  code/modules/vehicles/bike.dm
Labels: ready for review

#2335 Minor inflatable refactor.
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/game/objects/structures/inflatable.dm
  code/modules/fabrication/designs/general/designs_tools.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
Labels: ready for review

#2424 fix: adjust mob's move direction, only if it is an initiator of movement
  code/datums/movement/mob.dm
  code/game/objects/structures/janicart.dm
  code/game/objects/structures/stool_bed_chair_nest_sofa/wheelchair.dm
Labels: ready for review

#2417 Fix slurred speech.
  code/modules/mob/mob_helpers.dm
Labels: ready for review

#2411 Small changes from #2204
  code/__defines/colors.dm
  code/game/machinery/slide_projector.dm
  code/game/objects/item.dm
  code/modules/client/preference_setup/general/02_body.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/multiz/level_data.dm
  code/modules/overmap/overmap_object.dm
  maps/~mapsystem/maps.dm
  mods/content/mouse_highlights/mouse_highlight_client.dm
Labels: ready for review

#2395 Fixes click catcher coverage.
  code/_helpers/turfs.dm
  code/_onclick/click.dm
  code/_onclick/hud/hud.dm
  code/modules/client/client_procs.dm
Labels: ready for review

#2391 Tidying up a half-finished movable screen object removal.
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/ability_screen_objects.dm
  code/_onclick/hud/action.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/movable_screen_objects.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_defines.dm
  nebula.dme
Labels: ready for review

#2430 Fixed terminal from runtiming in nullspace on init.
  code/modules/power/terminal.dm
Labels: ready for review

#2427 Lowered gibbing throwforce.
  code/__defines/items_clothing.dm
  code/modules/organs/external/_external.dm
Labels: ready for review

#2429 Fix pipes atmos_init runtiming in nullspace
  code/modules/atmospherics/pipes.dm
Labels: ready for review

#2426 Clamps incision size to minimum bleed threshold.
  code/game/dna/dna2_helpers.dm
  code/modules/mob/living/carbon/human/appearance.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/external/wounds/wound.dm
  code/modules/organs/internal/brain.dm
  code/modules/organs/organ.dm
  code/modules/surgery/generic.dm
  mods/species/neoavians/datum/language.dm
Labels: ready for review

#2431 cached_json_code() returns a copy to avoid cache mutation.
  code/_helpers/lists.dm
Labels: ready for review

#2433 Fix mmi_holder qdel loop and switch langserver warning
  code/modules/mob/mob_helpers.dm
  code/modules/organs/internal/posibrain.dm
Labels: ready for review

#2408 Stole a bunch of tweaks from Naxodile's wyverm branch.
  code/__defines/unit_tests.dm
  code/controllers/subsystems/jobs.dm
  code/game/machinery/suit_cycler.dm
  code/game/objects/items/weapons/defib.dm
  code/game/objects/items/weapons/storage/med_pouch.dm
  code/game/objects/items/weapons/storage/toolbox.dm
  code/modules/atmospherics/components/unary/tank.dm
  code/modules/client/preference_setup/occupation/occupation.dm
  code/modules/clothing/_clothing.dm
  code/modules/clothing/spacesuits/void/void.dm
  code/modules/detectivework/tools/sample_kits/_sample_kit.dm
  code/modules/materials/definitions/solids/materials_solid_metal.dm
  code/modules/mob/language/alien/monkey.dm
  code/modules/mob/language/human/human.dm
  code/modules/mob/living/silicon/ai/latejoin.dm
  code/modules/organs/external/_external.dm
  code/modules/power/fusion/core/core_field.dm
  code/modules/reagents/dispenser/dispenser2.dm
  code/modules/reagents/dispenser/dispenser_presets.dm
  code/modules/reagents/storage/pill_bottle_subtypes.dm
  code/modules/surgery/necrotic.dm
  code/unit_tests/equipment_tests.dm
  code/unit_tests/map_tests.dm
  code/unit_tests/mob_tests.dm
  code/unit_tests/zas_tests.dm
  maps/~mapsystem/maps_unit_testing.dm
  nebula.dme
Labels: ready for review

#2415 Adding basic secret loading subsystem.
  code/__defines/subsystems.dm
  code/controllers/subsystems/initialization/modpacks.dm
  code/controllers/subsystems/initialization/secrets.dm
  code/controllers/subsystems/initialization/webhooks.dm
  code/modules/admin/admin_verbs.dm
  code/modules/hotloading/_admin.dm
  code/modules/hotloading/note.dm
  code/unit_tests/_includes.dm
  code/unit_tests/secrets.dm
  code/unit_tests/~unit_test_types.dm
  data/secrets/example/secret_example_random_one.json
  data/secrets/example/secret_example_random_three.json
  data/secrets/example/secret_example_random_two.json
  data/secrets/example/secret_example_single.json
  data/secrets/example/secret_note.dmi
  maps/~mapsystem/maps.dm
  mods/_modpack.dm
  nebula.dme
  test/check-paths.sh
  test/run-test.sh
Labels: ready for review

#2348 Refactoring skill book use to allow for adjacent reading.
  code/game/objects/items/books/skill_book.dm
Labels: ready for review

#2456 Network lock adjustments
  code/game/machinery/_machines_base/stock_parts/network_lock.dm
Labels: ready for review

#2449 Cache the pipe sound
  code/modules/atmospherics/pipes.dm
Labels: ready for review

#2437 Fixes structure double parent call.
  code/game/objects/structures/__structure.dm
  code/game/objects/structures/_structure_construction.dm
  code/game/objects/structures/window.dm
  mods/species/ascent/mobs/insectoid_egg.dm
Labels: ready for review

#2447 Temporarily swaps multitools out for variable tools.
  code/game/objects/items/weapons/material/kitchen.dm
  code/game/objects/items/weapons/material/knives.dm
  code/game/objects/items/weapons/material/swiss.dm
  code/game/objects/items/weapons/surgery_tools.dm
  code/game/objects/items/weapons/tape.dm
  code/modules/power/cable.dm
Labels: ready for review

#2453 Removes powered() checks
  code/game/area/areas.dm
  code/game/machinery/air_sensor.dm
  code/game/machinery/flasher.dm
  code/game/machinery/igniter.dm
  code/game/machinery/pager.dm
  code/game/machinery/portable_turret.dm
  code/game/machinery/recharger.dm
  code/modules/atmospherics/components/binary_devices/pump.dm
  code/modules/awaymissions/gateway.dm
  code/modules/mob/living/silicon/ai/power.dm
  code/modules/overmap/disperser/disperser_console.dm
  code/modules/overmap/disperser/disperser_fire.dm
  code/modules/overmap/ships/computers/sensors.dm
  code/modules/overmap/ships/machines/ion_thruster.dm
  code/modules/power/debug_items.dm
  code/modules/power/lighting.dm
  code/modules/research/design_database.dm
Labels: ready for review

#2458 Partially reverts vote UI changes.
  code/datums/vote/gamemode.dm
  code/datums/vote/transfer.dm
  code/datums/vote/vote.dm
Labels: ready for review
